### ISSUE TITLE
error in run lower resolution example

### ISSUE THREAD

**Issue by cchuang123456** [iris-edu/backprojection#2]
Hello,
    I have installed backprojection code. When I type ((BP) user@csulxg:/mnt/2D97AD940A9AD661/project/BP_example/backprojection-main$ python src/back_projection_r2.py -m 7.8 -y 55.030 -x -158.522 -z 28 -n AU -t 2020-07-22T06:12:44 -l -f 5), hoping to run a low-resolution example, I meet an error as follow:

[INFO] Adding S1.AUBSH to stack list (31), weight = 1.00
[INFO] Adding S1.AULRC to stack list (32), weight = 1.00
[INFO] Adding S1.AUNRC to stack list (33), weight = 1.00
[INFO] Adding S1.AUPHS to stack list (34), weight = 1.00
[INFO] Adding S1.AUTOO to stack list (35), weight = 1.00
[INFO] Adding ND.KOUNC to stack list (36), weight = 1.00
[WARN] Skipped, channel BHZ of Net.Sta AU.FITZ because no P-wave arrival
[WARN] Skipped, channel BHZ of Net.Sta S1.AUPHS because no P-wave arrival
[TIME] All stations for grid points 100/182 in 38.3 seconds
[WARN] Skipped, channel BHZ of Net.Sta S1.AULRC because no P-wave arrival
[WARN] Skipped, channel BHZ of Net.Sta AU.ARMA because no P-wave arrival
[WARN] Skipped, channel BHZ of Net.Sta AU.QLP because no P-wave arrival
[TIME] Stack END in 63.7 seconds
[TIME] Stack_root done in 0.257 second
[INFO] Averaging the beams
[INFO] In Hann: Integrate 182 beams over a 5 s window
[INFO] In Hann: half_window 2.5, stack_start -32.5, stack_end 152.5
[TIME] Beam averaging done in 1.86 seconds
[INFO] Time averaging the stacked traces and final resampling
[INFO] Stack decimation every 4 samples
[INFO] In Hann: Integrate 182 beams over a 10.0 s window
[INFO] In Hann: half_window 5.0, stack_start -35.0, stack_end 155.0
[TIME] Time averaging done in 0.916 second
[TIME] Stack root done in 0.064 second
[INFO] Global max location (55.03, -158.692)
[INFO] The global max is 10.87 km from the event < 1000
[TIME] Maximum amplitude found in 0.103 second
[TIME] Cumulative stack computed in 0.028 second
[INFO] Creating the animation
Traceback (most recent call last):
  File "/mnt/2D97AD940A9AD661/project/BP_example/backprojection-main/src/back_projection_r2.py", line 1713, in <module>
    make_animation(stack_start, stack_end, stack_amp, stack_amp_loc, stack_max, stack_max_loc, global_max,
  File "/mnt/2D97AD940A9AD661/project/BP_example/backprojection-main/src/back_projection_r2.py", line 705, in make_animation
    plt.savefig(os.path.join(scratch_dir, f'{file_tag}_'
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2342, in print_figure
    self.figure.draw(renderer)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/figure.py", line 3175, in draw
    mimage._draw_list_compositing_images(
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3064, in draw
    mimage._draw_list_compositing_images(
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/lines.py", line 796, in draw
    gc.set_dashes(*self._dash_pattern)
  File "/home/user/anaconda3/envs/BP/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 959, in set_dashes
    raise ValueError(
ValueError: At least one value in the dash list must be positive

Can you give me some advice?

**Comment by manoch-iris** [comment]
Dear @cchuang123456, thank you for contacting us. This error is related to your installation environment. We recently installed the same package on a different platform using matplotlib==3.5.2 in our requirements.txt file and it is running with no issue. Would you please try that and let me know if that addresses your problem?  Best, --manoch

**Comment by cchuang123456** [comment]
> Dear @cchuang123456, thank you for contacting us. This error is related to your installation environment. We recently installed the same package on a different platform using matplotlib==3.5.2 in our requirements.txt file and it is running with no issue. Would you please try that and let me know if that addresses your problem? Best, --manoch

Thanks, I can run it successfully.
Best wishes!
chuanchao

**Comment by manoch-iris** [comment]
Wonderful! Thank you for letting me know.
Best,
--manoch
